# shared/strategies/definitions.py
# Zentrale Datenbank aller Saisonalstrategien als strukturierte Python-Dicts.
# Nur Metadaten — keine Berechnungslogik (die ist in den jeweiligen Modulen).
#
# Felder pro Strategie:
#   name         : Anzeigename
#   kategorie    : z.B. "Jahr", "Monat", "Event", "Woche", ...
#   asset        : Markt / Assetklasse
#   zeitfenster  : Kalenderperiode als Text
#   logik        : Long-/Short-Logik (kurz)
#   staerke      : "gering" | "gering–mittel" | "mittel" | "mittel–hoch" | "hoch"
#   quelle       : Primärquelle / Typ
#   modul        : Python-Modul mit Berechnungslogik (None = noch nicht implementiert)
#   tags         : Liste von Schlagworten für spätere Filterung

# ── Konstanten ────────────────────────────────────────────────────────────────

KATEGORIEN = [
    "Jahr",
    "Monat",
    "Quartal",
    "Monatsanfang/-ende",
    "Monatsmitte",
    "Feiertag",
    "Event",
    "Woche",
    "Tag",
]

STAERKEN = ["gering", "gering–mittel", "mittel", "mittel–hoch", "hoch"]

# ── Strategiedatenbank ────────────────────────────────────────────────────────

STRATEGIES = [

    # ── JAHRES-STRATEGIEN ──────────────────────────────────────────────────────
    {
        "name": "Sell in May / Halloween Effect",
        "kategorie": "Jahr",
        "asset": "Aktien, Indizes, ETFs",
        "zeitfenster": "Long ca. 31.10–30.04, Flat 01.05–31.10",
        "logik": "Nur Winterhalbjahr investiert",
        "staerke": "mittel–hoch",
        "quelle": "Klassische Kalenderanomalie, edu-Blogs",
        "modul": None,
        "tags": ["halloween", "sell-in-may", "winter", "sommer", "index"],
    },
    {
        "name": "Best Six Months Strategie",
        "kategorie": "Jahr",
        "asset": "US-Indizes",
        "zeitfenster": "Nov–Apr",
        "logik": "Long in besten 6 Monaten",
        "staerke": "mittel–hoch",
        "quelle": "Variante Halloween-Effekt",
        "modul": None,
        "tags": ["halloween", "sell-in-may", "winter", "index"],
    },
    {
        "name": "Worst Six Months Hedge",
        "kategorie": "Jahr",
        "asset": "US-Indizes",
        "zeitfenster": "Mai–Okt",
        "logik": "Hedge/Underweight in schwächeren 6 Monaten",
        "staerke": "mittel",
        "quelle": "Variante Halloween-Effekt",
        "modul": None,
        "tags": ["halloween", "sell-in-may", "sommer", "hedge"],
    },
    {
        "name": "Winter Effect (Nov–Apr vs. Mai–Okt)",
        "kategorie": "Jahr",
        "asset": "Aktien, Indizes",
        "zeitfenster": "Nov–Apr vs. Mai–Okt",
        "logik": "Übergewicht Winter, Untergewicht Sommer",
        "staerke": "mittel–hoch",
        "quelle": "Akademische Studien",
        "modul": None,
        "tags": ["winter", "sommer", "index"],
    },
    {
        "name": "Sommerflaute / Summer Doldrums",
        "kategorie": "Jahr",
        "asset": "Aktien, Indizes",
        "zeitfenster": "Mai–Sep",
        "logik": "Risikoabbau im Sommer",
        "staerke": "mittel",
        "quelle": "TrendSpider",
        "modul": None,
        "tags": ["sommer", "index", "risiko"],
    },
    {
        "name": "Retail Q4 Effekt",
        "kategorie": "Jahr",
        "asset": "Retail-Aktien, Konsum-ETFs",
        "zeitfenster": "Okt–Dez",
        "logik": "Long Retail vor Holiday Season",
        "staerke": "mittel",
        "quelle": "Seasonality-Blogs, TrendSpider",
        "modul": None,
        "tags": ["retail", "q4", "sektor"],
    },
    {
        "name": "Tech Q1 Effekt",
        "kategorie": "Jahr",
        "asset": "Technologie-Aktien",
        "zeitfenster": "Jan–März",
        "logik": "Long Tech im 1. Quartal",
        "staerke": "gering–mittel",
        "quelle": "TrendSpider",
        "modul": None,
        "tags": ["tech", "q1", "sektor"],
    },
    {
        "name": "Utilities Summer Effekt",
        "kategorie": "Jahr",
        "asset": "Versorger-Aktien",
        "zeitfenster": "Frühling–Sommer",
        "logik": "Long Utilities vor Sommer",
        "staerke": "gering–mittel",
        "quelle": "TrendSpider",
        "modul": None,
        "tags": ["utilities", "sommer", "sektor"],
    },
    {
        "name": "Agrar-Planting Season",
        "kategorie": "Jahr",
        "asset": "Agrar-Futures",
        "zeitfenster": "Spätwinter–Frühjahr",
        "logik": "Long in typischer Pre-Planting-Phase",
        "staerke": "mittel–hoch",
        "quelle": "Rohstoff-Seasonality-Research",
        "modul": None,
        "tags": ["agrar", "futures", "rohstoff"],
    },
    {
        "name": "Agrar-Harvest Season",
        "kategorie": "Jahr",
        "asset": "Agrar-Futures",
        "zeitfenster": "Herbst",
        "logik": "Short/Underweight in typischer Überangebots-Phase",
        "staerke": "mittel–hoch",
        "quelle": "Rohstoff-Seasonality-Research",
        "modul": None,
        "tags": ["agrar", "futures", "rohstoff", "short"],
    },
    {
        "name": "Energy Heating Season",
        "kategorie": "Jahr",
        "asset": "Gas, Heating Oil",
        "zeitfenster": "Herbst–Winter",
        "logik": "Long vor Heizsaison",
        "staerke": "mittel",
        "quelle": "Commodity-Studien",
        "modul": None,
        "tags": ["energie", "gas", "futures", "rohstoff", "winter"],
    },
    {
        "name": "Driving Season (Gasoline)",
        "kategorie": "Jahr",
        "asset": "Gasoline-Futures",
        "zeitfenster": "späte Frühling–Sommer",
        "logik": "Long vor Driving Season",
        "staerke": "mittel",
        "quelle": "Commodity-Studien",
        "modul": None,
        "tags": ["energie", "gasoline", "futures", "rohstoff", "sommer"],
    },
    {
        "name": "Gold Safe Haven Winter",
        "kategorie": "Jahr",
        "asset": "Gold",
        "zeitfenster": "Herbst–Winter",
        "logik": "Übergewicht Gold in volatilen Wintermonaten",
        "staerke": "gering–mittel",
        "quelle": "Praxis-Blogs",
        "modul": None,
        "tags": ["gold", "rohstoff", "winter", "safe-haven"],
    },
    {
        "name": "FX Sell in May (Risk-On FX)",
        "kategorie": "Jahr",
        "asset": "High-Beta FX-Paare",
        "zeitfenster": "Mai–Okt",
        "logik": "Underweight Risk-On-FX im Sommer",
        "staerke": "gering–mittel",
        "quelle": "FX-Seasonality-Arbeiten",
        "modul": None,
        "tags": ["fx", "währung", "sommer", "sell-in-may"],
    },
    {
        "name": "Sell Vol in Summer",
        "kategorie": "Jahr",
        "asset": "Vol-Produkte (VXX, VIX-Futures)",
        "zeitfenster": "Sommermonate",
        "logik": "Short Vol in ruhigen Sommern",
        "staerke": "gering–mittel",
        "quelle": "Praxis-Blogs",
        "modul": None,
        "tags": ["vix", "volatilität", "sommer", "short"],
    },
    {
        "name": "Commodity Calendar Spreads",
        "kategorie": "Jahr",
        "asset": "Spreads (z.B. CL-Spreads)",
        "zeitfenster": "plant-/harvest-abhängig",
        "logik": "Long saisonal günstige Month-Spreads",
        "staerke": "mittel–hoch",
        "quelle": "Managed-Futures-Literatur",
        "modul": None,
        "tags": ["rohstoff", "futures", "spread"],
    },
    {
        "name": "Crisis-Hedge Seasonality",
        "kategorie": "Jahr",
        "asset": "Tail-Hedges (Gold, VIX, Bonds)",
        "zeitfenster": "bestimmte Monate/Jahresphasen",
        "logik": "zeitlich begrenzter Hedge",
        "staerke": "gering–mittel",
        "quelle": "Hedge-Fonds-Research",
        "modul": None,
        "tags": ["hedge", "gold", "vix", "bonds"],
    },
    {
        "name": "Sector Rotation Seasonal",
        "kategorie": "Jahr",
        "asset": "Sektor-ETFs",
        "zeitfenster": "je Quartal andere Sektoren",
        "logik": "Rotationsschema (z.B. Q1 Tech, Q4 Retail)",
        "staerke": "gering–mittel",
        "quelle": "edukative Artikel",
        "modul": None,
        "tags": ["sektor", "rotation", "etf"],
    },

    # ── MONATS-STRATEGIEN ──────────────────────────────────────────────────────
    {
        "name": "December Effect",
        "kategorie": "Monat",
        "asset": "Aktien, Indizes",
        "zeitfenster": "Dezember",
        "logik": "Übergewicht Aktien in Dez",
        "staerke": "mittel",
        "quelle": "Monatsanomalien-Papers",
        "modul": None,
        "tags": ["dezember", "index", "jahresende"],
    },
    {
        "name": "January Effect (Small Caps)",
        "kategorie": "Monat",
        "asset": "Small-Cap-Aktien, Indizes",
        "zeitfenster": "Ende Dez–Jan",
        "logik": "Long Small Caps um Jahreswechsel",
        "staerke": "mittel",
        "quelle": "Monatsanomalien-Papers",
        "modul": "januar_trifecta",
        "tags": ["januar", "small-cap", "jahreswechsel"],
    },
    {
        "name": "Turn-of-the-Year Effect",
        "kategorie": "Monat",
        "asset": "Aktien, Indizes",
        "zeitfenster": "letzte Dez-Tage + erste Jan-Tage",
        "logik": "Long Markt um Jahreswechsel",
        "staerke": "mittel",
        "quelle": "Monatsanomalien-Papers",
        "modul": None,
        "tags": ["januar", "dezember", "jahreswechsel", "index"],
    },
    {
        "name": "September Effect",
        "kategorie": "Monat",
        "asset": "Aktien, Indizes",
        "zeitfenster": "September",
        "logik": "Untergewicht / Short Aktien in Sep",
        "staerke": "gering–mittel",
        "quelle": "Monatsanomalien-Papers",
        "modul": None,
        "tags": ["september", "index", "short"],
    },
    {
        "name": "Best Month Strategien",
        "kategorie": "Monat",
        "asset": "Indizes, Sektoren",
        "zeitfenster": "je nach Markt (z.B. Apr, Nov)",
        "logik": "Long nur in historisch stärksten Monaten",
        "staerke": "gering–mittel",
        "quelle": "Monatsanomalien-Übersichten",
        "modul": None,
        "tags": ["monat", "index", "best-months"],
    },
    {
        "name": "Crypto Month-of-Year Bias",
        "kategorie": "Monat",
        "asset": "BTC, ETH",
        "zeitfenster": "z.B. saisonale Stärke in Q4",
        "logik": "Übergewicht in starken Monaten",
        "staerke": "gering",
        "quelle": "wenige Zyklen",
        "modul": None,
        "tags": ["crypto", "bitcoin", "q4"],
    },
    {
        "name": "Front-Running Roll-Yield (Rohstoffe)",
        "kategorie": "Monat",
        "asset": "Commodity-Futures",
        "zeitfenster": "vor Standard-Rollterminen",
        "logik": "Long/Short je nach Saisonstruktur",
        "staerke": "mittel–hoch",
        "quelle": "Rohstoff-Forschung",
        "modul": None,
        "tags": ["rohstoff", "futures", "roll"],
    },

    # ── QUARTALS-STRATEGIEN ────────────────────────────────────────────────────
    {
        "name": "Q4 Outperformance",
        "kategorie": "Quartal",
        "asset": "Aktien, Indizes",
        "zeitfenster": "Okt–Dez",
        "logik": "Übergewicht Q4",
        "staerke": "mittel",
        "quelle": "Versch. Studien, Blogs",
        "modul": None,
        "tags": ["q4", "index", "jahresende"],
    },
    {
        "name": "Q1 Mean Reversion",
        "kategorie": "Quartal",
        "asset": "Aktien",
        "zeitfenster": "Jan–März nach schwachem Q4",
        "logik": "Long Rebound im Q1",
        "staerke": "gering–mittel",
        "quelle": "Praxis-Blogs",
        "modul": None,
        "tags": ["q1", "mean-reversion", "januar"],
    },

    # ── MONATSANFANG/-ENDE ─────────────────────────────────────────────────────
    {
        "name": "Turn-of-the-Month (ToM) Standard",
        "kategorie": "Monatsanfang/-ende",
        "asset": "Aktienindizes, ETFs",
        "zeitfenster": "letzte 4 + erste 3 Handelstage",
        "logik": "Long nur im ToM-Fenster",
        "staerke": "hoch",
        "quelle": "Kalenderanomalie-Literatur",
        "modul": None,
        "tags": ["tom", "monatsanfang", "monatsende", "index"],
    },
    {
        "name": "ToM Simple (Ultimo–1. Handelstag)",
        "kategorie": "Monatsanfang/-ende",
        "asset": "ETFs (SPY)",
        "zeitfenster": "letzter Handelstag + 1. Handelstag",
        "logik": "Kauf Ultimo, Verkauf 1. Handelstag",
        "staerke": "mittel–hoch",
        "quelle": "vereinfachte ToM-Variante",
        "modul": None,
        "tags": ["tom", "monatsanfang", "monatsende", "spy"],
    },
    {
        "name": "End-of-Month Treasuries",
        "kategorie": "Monatsanfang/-ende",
        "asset": "T-Bond-ETFs",
        "zeitfenster": "letzte 2 Handelstage des Monats",
        "logik": "Long TLT o.Ä.",
        "staerke": "mittel",
        "quelle": "edu-Artikel",
        "modul": None,
        "tags": ["monatsende", "bonds", "treasuries", "tlt"],
    },
    {
        "name": "FX Month-End Rebalancing",
        "kategorie": "Monatsanfang/-ende",
        "asset": "Majors (EURUSD, GBPUSD)",
        "zeitfenster": "Monatsultimo",
        "logik": "Intraday-Signale auf Rebalancing-Flows",
        "staerke": "mittel",
        "quelle": "FX-Rebalancing-Literatur",
        "modul": None,
        "tags": ["fx", "monatsende", "rebalancing"],
    },

    # ── MONATSMITTE ────────────────────────────────────────────────────────────
    {
        "name": "Middle-of-the-Month / Payday Effekt",
        "kategorie": "Monatsmitte",
        "asset": "S&P 500 / SPY",
        "zeitfenster": "15.–16. Kalendertag",
        "logik": "Long SPY 15. close–16. close",
        "staerke": "mittel",
        "quelle": "Composite-Kalender-Strategien",
        "modul": None,
        "tags": ["monatsmitte", "spy", "payday"],
    },

    # ── FEIERTAGS-STRATEGIEN ───────────────────────────────────────────────────
    {
        "name": "Santa Claus Rally",
        "kategorie": "Feiertag",
        "asset": "Aktien, Indizes",
        "zeitfenster": "letzte 5 Dez-Tage + erste 2 Jan-Tage",
        "logik": "Long Index in diesem 7-Tage-Fenster",
        "staerke": "mittel",
        "quelle": "Holiday-Literatur",
        "modul": "januar_trifecta",
        "tags": ["santa-claus", "dezember", "januar", "feiertag", "index"],
    },
    {
        "name": "Allgemeiner Holiday Effect",
        "kategorie": "Feiertag",
        "asset": "Aktien, Indizes",
        "zeitfenster": "1–3 Tage vor Feiertagen",
        "logik": "Long Index vor Feiertag",
        "staerke": "mittel",
        "quelle": "Holiday-Papers",
        "modul": None,
        "tags": ["feiertag", "index", "holiday-effect"],
    },
    {
        "name": "Thanksgiving Rally (USA)",
        "kategorie": "Feiertag",
        "asset": "US-Aktien",
        "zeitfenster": "Woche vor Thanksgiving",
        "logik": "Long US-Index",
        "staerke": "gering–mittel",
        "quelle": "Praxis-Blogs",
        "modul": None,
        "tags": ["thanksgiving", "november", "feiertag", "usa"],
    },
    {
        "name": "Easter Effect",
        "kategorie": "Feiertag",
        "asset": "Aktien",
        "zeitfenster": "um Ostern",
        "logik": "Long vor Ostern",
        "staerke": "gering",
        "quelle": "Mischbefunde in Literatur",
        "modul": None,
        "tags": ["ostern", "feiertag"],
    },
    {
        "name": "Year-End Window Dressing",
        "kategorie": "Feiertag",
        "asset": "Fonds-Holdings, Large Caps",
        "zeitfenster": "Dez (insb. letzte Woche)",
        "logik": "Long 'Winners' vor Jahresende",
        "staerke": "gering–mittel",
        "quelle": "Fonds-Literatur",
        "modul": None,
        "tags": ["dezember", "window-dressing", "jahresende", "fonds"],
    },
    {
        "name": "VIX December Pre-Holiday Short",
        "kategorie": "Feiertag",
        "asset": "VIX-ETFs (VIXY)",
        "zeitfenster": "VIX-Dez-Verfall bis 24.12.",
        "logik": "Short VIXY im Fenster",
        "staerke": "mittel",
        "quelle": "quant. edu-Artikel",
        "modul": None,
        "tags": ["vix", "dezember", "short", "feiertag"],
    },

    # ── EVENT-STRATEGIEN ───────────────────────────────────────────────────────
    {
        "name": "Pre-FOMC Drift",
        "kategorie": "Event",
        "asset": "US-Aktien, SPY",
        "zeitfenster": "Tage vor FOMC-Meetings",
        "logik": "Long Index bis Meeting",
        "staerke": "mittel–hoch",
        "quelle": "FOMC-Anomalie-Arbeiten",
        "modul": None,
        "tags": ["fomc", "fed", "zentralbank", "drift"],
    },
    {
        "name": "FOMC-Meeting Day Effekt",
        "kategorie": "Event",
        "asset": "US-Aktien, SPY",
        "zeitfenster": "FOMC-Tag",
        "logik": "Long SPY vor/auf FOMC-Tag",
        "staerke": "mittel–hoch",
        "quelle": "empirische Arbeiten",
        "modul": None,
        "tags": ["fomc", "fed", "zentralbank"],
    },
    {
        "name": "Options Expiration Week (Monthly OPEX)",
        "kategorie": "Event",
        "asset": "SPY, Large Caps",
        "zeitfenster": "Woche vor 3. Freitag",
        "logik": "Long SPY Fr–Do der Verfallswoche",
        "staerke": "hoch",
        "quelle": "Calendar-Case-Studies",
        "modul": None,
        "tags": ["opex", "options", "verfall", "spy"],
    },
    {
        "name": "Quadruple Witching Days",
        "kategorie": "Event",
        "asset": "Aktien, Indizes, Futures",
        "zeitfenster": "März, Jun, Sep, Dez-Verfall",
        "logik": "Long/Short-Setups rund um Expiration",
        "staerke": "mittel",
        "quelle": "Derivate-Literatur",
        "modul": None,
        "tags": ["opex", "options", "futures", "verfall", "quadruple-witching"],
    },
    {
        "name": "Non-Farm Payrolls (NFP) Day",
        "kategorie": "Event",
        "asset": "FX, Indizes",
        "zeitfenster": "1. Freitag im Monat (USA)",
        "logik": "Intraday-Bias in Richtung Volatilität",
        "staerke": "gering–mittel",
        "quelle": "Makro-Event-Studien",
        "modul": None,
        "tags": ["nfp", "makro", "fx", "volatilität"],
    },
    {
        "name": "Earnings Season Index Bias",
        "kategorie": "Event",
        "asset": "Indizes, Sektoren",
        "zeitfenster": "4x pro Jahr",
        "logik": "Long Markt in Haupt-Earnings-Phase",
        "staerke": "gering–mittel",
        "quelle": "Praxis-Strategien",
        "modul": None,
        "tags": ["earnings", "quartalsbericht", "index"],
    },
    {
        "name": "Pre-Earnings Season Retail/Tech",
        "kategorie": "Event",
        "asset": "Retail, Tech",
        "zeitfenster": "Wochen vor Haupt-Earnings-Monaten",
        "logik": "Long sektorspezifisch",
        "staerke": "gering–mittel",
        "quelle": "Trading-Blogs",
        "modul": None,
        "tags": ["earnings", "retail", "tech", "sektor"],
    },
    {
        "name": "Dividend Capture (Ex-Dividend)",
        "kategorie": "Event",
        "asset": "Dividendenaktien",
        "zeitfenster": "wenige Tage vor Ex-Date",
        "logik": "Kauf vor Ex-Datum, Verkauf kurz danach",
        "staerke": "gering–mittel",
        "quelle": "Dividenden-Literatur",
        "modul": None,
        "tags": ["dividende", "ex-date", "aktien"],
    },
    {
        "name": "Ex-Dividend Season (z.B. April in DE)",
        "kategorie": "Event",
        "asset": "Lokale Märkte (z.B. DAX)",
        "zeitfenster": "lokale Dividendenmonate",
        "logik": "Long vor/short nach Ex-Datum-Clustern",
        "staerke": "gering–mittel",
        "quelle": "Markt-spezifische Analysen",
        "modul": None,
        "tags": ["dividende", "ex-date", "dax", "deutschland"],
    },
    {
        "name": "Crypto Halving-Zyklus (BTC)",
        "kategorie": "Event",
        "asset": "Bitcoin",
        "zeitfenster": "Monate vor/nach Halvings",
        "logik": "Long BTC in Halving-Fenstern",
        "staerke": "gering–mittel",
        "quelle": "Crypto-Research",
        "modul": None,
        "tags": ["crypto", "bitcoin", "halving"],
    },

    # ── WOCHEN-STRATEGIEN ──────────────────────────────────────────────────────
    {
        "name": "Day-of-the-Week Standard",
        "kategorie": "Woche",
        "asset": "Aktien",
        "zeitfenster": "alle Wochentage",
        "logik": "Trade auf Basis historischer Wochentag-Returns",
        "staerke": "gering–mittel",
        "quelle": "klassische Studien",
        "modul": None,
        "tags": ["wochentag", "aktien"],
    },
    {
        "name": "Monday Effect (negativ)",
        "kategorie": "Woche",
        "asset": "Aktien",
        "zeitfenster": "Montage",
        "logik": "Underweight Montag, ggf. Short intraday",
        "staerke": "gering",
        "quelle": "neuere Daten: schwach",
        "modul": None,
        "tags": ["montag", "wochentag", "short"],
    },
    {
        "name": "Friday Effect (positiv)",
        "kategorie": "Woche",
        "asset": "Aktien",
        "zeitfenster": "Freitage",
        "logik": "Long in Richtung Wochenclose",
        "staerke": "gering–mittel",
        "quelle": "Day-of-Week-Literatur",
        "modul": None,
        "tags": ["freitag", "wochentag"],
    },
    {
        "name": "Turnaround Tuesday",
        "kategorie": "Woche",
        "asset": "US-Aktien",
        "zeitfenster": "Dienstag (nach schwachem Montag)",
        "logik": "Long Mean-Reversion am Dienstag",
        "staerke": "gering–mittel",
        "quelle": "Trading-Blogs",
        "modul": None,
        "tags": ["dienstag", "wochentag", "mean-reversion"],
    },

    # ── TAGES-STRATEGIEN ───────────────────────────────────────────────────────
    {
        "name": "Intraday Opening/Closing Seasonality",
        "kategorie": "Tag",
        "asset": "Einzelaktien, Indizes",
        "zeitfenster": "Markteröffnung/-schluss",
        "logik": "Intraday-Bias (z.B. Open Reversal)",
        "staerke": "gering–mittel",
        "quelle": "Intraday-Seasonality-Research",
        "modul": None,
        "tags": ["intraday", "open", "close", "aktien"],
    },

    # ── KAEPPEL-STRATEGIEN ─────────────────────────────────────────────────────
    {
        "name": "Kaeppel Ultimate Holiday System",
        "kategorie": "Feiertag",
        "asset": "S&P 500, Dow Jones, ETFs",
        "zeitfenster": "3 Handelstage vor + 3 Handelstage nach jedem Marktfeiertag",
        "logik": "Long Index/ETF über die 6-Tage-Periode um Feiertage",
        "staerke": "hoch",
        "quelle": "Kaeppel 'Seasonal Stock Market Trends'",
        "modul": "kaeppel",
        "tags": ["kaeppel", "feiertag", "holiday", "sp500", "dow"],
    },
    {
        "name": "Kaeppel Ultimate Monthly Days System",
        "kategorie": "Monatsanfang/-ende",
        "asset": "S&P 500, Dow",
        "zeitfenster": "Best/Worst Trading Days innerhalb eines Monats",
        "logik": "Long an statistisch besten Tagen pro Monat",
        "staerke": "mittel–hoch",
        "quelle": "Kaeppel's Monthly Patterns Research",
        "modul": "kaeppel",
        "tags": ["kaeppel", "tdom", "monat", "sp500"],
    },
    {
        "name": "Kaeppel Simple Monthly Seasonal",
        "kategorie": "Monat",
        "asset": "S&P 500/Dow",
        "zeitfenster": "Best Months: Nov, Dez, Apr, Jul",
        "logik": "Long nur in historisch stärksten 4 Monaten pro Jahr",
        "staerke": "hoch",
        "quelle": "Better System Trader Podcast",
        "modul": "kaeppel",
        "tags": ["kaeppel", "best-months", "sp500", "dow"],
    },
    {
        "name": "Kaeppel Seasonal Sector System",
        "kategorie": "Jahr",
        "asset": "Sektor-ETFs (Tech, Retail, Utilities)",
        "zeitfenster": "6 Trades/Jahr nach Saisonmustern",
        "logik": "Rotation: Q4 Retail, Q1 Tech, Sommer Utilities etc.",
        "staerke": "mittel",
        "quelle": "Kaeppel Sector Research",
        "modul": "kaeppel",
        "tags": ["kaeppel", "sektor", "rotation", "etf"],
    },
    {
        "name": "Known Trend Index (KTI)",
        "kategorie": "Jahr",
        "asset": "S&P 500 + mehrere Indizes",
        "zeitfenster": "Kombination von 5+ Seasonal-Tendenzen",
        "logik": "Wenn ≥4 von 5 Seasonal-Indikatoren bullish → aggressiv long",
        "staerke": "hoch",
        "quelle": "Kaeppel's Hauptinnovation",
        "modul": "kaeppel",
        "tags": ["kaeppel", "kti", "meta", "composite", "sp500"],
    },
    {
        "name": "Kaeppel Ultimate Election Cycle System",
        "kategorie": "Jahr",
        "asset": "S&P 500",
        "zeitfenster": "Post-election Yr1 schwach, Yr3 stark (Prä-Wahl)",
        "logik": "Übergewicht Jahr 3, Underweight Jahr 1 eines Präsidentschaftszyklus",
        "staerke": "mittel–hoch",
        "quelle": "Kaeppel Election Cycle Research",
        "modul": "kaeppel",
        "tags": ["kaeppel", "präsidentschaftszyklus", "election", "sp500"],
    },
    {
        "name": "Years Ending in 5 Effect",
        "kategorie": "Jahr",
        "asset": "S&P 500, Indizes",
        "zeitfenster": "Kalenderjahre endend auf 5 (2005, 2015, 2025...)",
        "logik": "Extra Long-Exposure in '-5' Jahren",
        "staerke": "mittel",
        "quelle": "Kaeppel's Decennial Cycles",
        "modul": "kaeppel",
        "tags": ["kaeppel", "dekadenzyklus", "decennial", "sp500"],
    },
    {
        "name": "LOPL (Long-Only Plus Leverage)",
        "kategorie": "Jahr",
        "asset": "Leveraged ETFs (UPRO, TQQQ)",
        "zeitfenster": "Kombination aller Kaeppel-Saisonals",
        "logik": "Long-only + 3x Leverage in stärksten Seasonal-Fenstern",
        "staerke": "hoch",
        "quelle": "Kaeppel's Leverage Model",
        "modul": "kaeppel",
        "tags": ["kaeppel", "leverage", "upro", "tqqq", "meta"],
    },

    # ── JANUAR TRIFECTA ────────────────────────────────────────────────────────
    {
        "name": "Januar Trifecta Ampelsystem",
        "kategorie": "Monat",
        "asset": "Aktien, Indizes (S&P 500)",
        "zeitfenster": "letzte 5 Dez-Tage + erste 5 Jan-Tage + ganzer Januar",
        "logik": "Ampel Grün/Gelb/Orange/Rot je nach Anzahl erfüllter Bedingungen",
        "staerke": "mittel–hoch",
        "quelle": "Stock Trader's Almanac / Yale Hirsch",
        "modul": "januar_trifecta",
        "tags": ["januar", "santa-claus", "january-barometer", "ampel", "meta"],
    },
    {
        "name": "Santa Claus Rally (Trifecta)",
        "kategorie": "Feiertag",
        "asset": "S&P 500, Indizes",
        "zeitfenster": "letzte 5 Handelstage Dez + erste 2 Jan-Tage",
        "logik": "Positiver SCR → bullishes Jahressignal",
        "staerke": "mittel",
        "quelle": "Stock Trader's Almanac",
        "modul": "januar_trifecta",
        "tags": ["santa-claus", "januar", "dezember", "trifecta"],
    },
    {
        "name": "First Five Days Indikator",
        "kategorie": "Monat",
        "asset": "S&P 500",
        "zeitfenster": "erste 5 Handelstage im Januar",
        "logik": "Positiv → bullishes Jahressignal",
        "staerke": "mittel",
        "quelle": "Stock Trader's Almanac",
        "modul": "januar_trifecta",
        "tags": ["januar", "first-five-days", "trifecta", "jahressignal"],
    },
    {
        "name": "January Barometer",
        "kategorie": "Monat",
        "asset": "S&P 500",
        "zeitfenster": "gesamter Januar",
        "logik": "Wie Januar → so das Jahr (85% historische Trefferquote)",
        "staerke": "mittel–hoch",
        "quelle": "Yale Hirsch / Stock Trader's Almanac",
        "modul": "januar_trifecta",
        "tags": ["januar", "january-barometer", "trifecta", "jahressignal"],
    },
]


# ── Hilfsfunktionen ────────────────────────────────────────────────────────────

def get_strategies_by_category(kategorie: str) -> list:
    """Gibt alle Strategien einer Kategorie zurück."""
    return [s for s in STRATEGIES if s["kategorie"] == kategorie]


def get_strategies_by_strength(min_staerke: str = "mittel") -> list:
    """
    Filtert Strategien nach Mindeststärke.
    Reihenfolge: gering < gering–mittel < mittel < mittel–hoch < hoch
    """
    rank = {s: i for i, s in enumerate(STAERKEN)}
    min_rank = rank.get(min_staerke, 0)
    return [s for s in STRATEGIES if rank.get(s["staerke"], 0) >= min_rank]


def get_strategies_by_tag(tag: str) -> list:
    """Gibt alle Strategien zurück, die ein bestimmtes Tag enthalten."""
    tag = tag.lower()
    return [s for s in STRATEGIES if tag in s.get("tags", [])]


def get_strategies_with_module() -> list:
    """Gibt alle Strategien zurück, die ein implementiertes Python-Modul haben."""
    return [s for s in STRATEGIES if s["modul"] is not None]
