-- ============================================================
-- tickers-Tabelle wiederherstellen + aus symbols.py befuellen
-- 270 Ticker | im Supabase SQL-Editor ausfuehren (DDL geht nicht via PostgREST)
-- ============================================================

CREATE TABLE IF NOT EXISTS tickers (
    ticker       TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    kategorie    TEXT NOT NULL,
    waehrung     TEXT DEFAULT 'USD',
    exchange     TEXT,
    beschreibung TEXT,
    aktiv        BOOLEAN DEFAULT TRUE,
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tickers_kategorie ON tickers (kategorie);
CREATE INDEX IF NOT EXISTS idx_tickers_name ON tickers (name);

-- RLS + read-only Policy fuer anon (Konvention der Marktdaten-Tabellen)
ALTER TABLE tickers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read" ON tickers;
CREATE POLICY "anon_read" ON tickers FOR SELECT TO anon USING (true);

-- GRANTs (service_role schreibt, anon liest) — gegen GRANT-Loss absichern
GRANT SELECT ON tickers TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON tickers TO service_role;

-- Populate (idempotent via ON CONFLICT)
INSERT INTO tickers (ticker, name, kategorie, waehrung, exchange, beschreibung, aktiv) VALUES
  ('^GSPC', 'S&P 500', 'US-Index', 'USD', 'NYSE', 'S&P 500 Index — 500 größte US-Unternehmen', TRUE),
  ('^DJI', 'Dow Jones', 'US-Index', 'USD', 'NYSE', 'Dow Jones Industrial Average — 30 Blue Chips', TRUE),
  ('^IXIC', 'Nasdaq Composite', 'US-Index', 'USD', 'NASDAQ', 'Nasdaq Composite — alle Nasdaq-gelisteten Aktien', TRUE),
  ('^NDX', 'Nasdaq 100', 'US-Index', 'USD', 'NASDAQ', 'Nasdaq 100 — Top 100 Nicht-Finanzwerte', TRUE),
  ('^RUT', 'Russell 2000', 'US-Index', 'USD', 'NYSE', 'Russell 2000 — 2000 Small-Cap US-Aktien', TRUE),
  ('^VIX', 'VIX Volatilitätsindex', 'Volatility', 'USD', 'CBOE', 'CBOE Volatility Index — S&P 500 Fear Gauge (30d implizite Vol)', TRUE),
  ('^VXN', 'VXN Nasdaq Volatilität', 'Volatility', 'USD', 'CBOE', 'CBOE Nasdaq-100 Volatility Index — Tech Fear Gauge', TRUE),
  ('^OVX', 'OVX Oil Volatilität', 'Volatility', 'USD', 'CBOE', 'CBOE Crude Oil Volatility Index — WTI Fear Gauge', TRUE),
  ('IBIT', 'iShares Bitcoin Trust ETF', 'US-ETF', 'USD', 'NYSE', 'iShares Bitcoin Trust ETF — Spot-Bitcoin ETF (BlackRock)', TRUE),
  ('SPY', 'SPDR S&P 500 ETF', 'US-ETF', 'USD', 'NYSE', 'Größter S&P 500 ETF — sehr hohe Liquidität', TRUE),
  ('QQQ', 'Invesco Nasdaq 100 ETF', 'US-ETF', 'USD', 'NASDAQ', 'Nasdaq 100 ETF — Tech-lastig', TRUE),
  ('IWM', 'iShares Russell 2000 ETF', 'US-ETF', 'USD', 'NYSE', 'Small-Cap US-Aktien ETF', TRUE),
  ('DIA', 'SPDR Dow Jones ETF', 'US-ETF', 'USD', 'NYSE', 'Dow Jones Industrial Average ETF', TRUE),
  ('TLT', 'iShares 20+ Year Treasury ETF', 'US-ETF', 'USD', 'NYSE', 'Langläufer US-Staatsanleihen ETF', TRUE),
  ('GLD', 'SPDR Gold ETF', 'US-ETF', 'USD', 'NYSE', 'Gold ETF — physisch hinterlegt', TRUE),
  ('SLV', 'iShares Silver ETF', 'US-ETF', 'USD', 'NYSE', 'Silber ETF', TRUE),
  ('USO', 'United States Oil ETF', 'US-ETF', 'USD', 'NYSE', 'Rohöl ETF (WTI)', TRUE),
  ('XLF', 'Financial Select Sector ETF', 'US-ETF', 'USD', 'NYSE', 'US-Finanzsektor ETF', TRUE),
  ('XLK', 'Technology Select Sector ETF', 'US-ETF', 'USD', 'NYSE', 'US-Technologiesektor ETF', TRUE),
  ('XLE', 'Energy Select Sector ETF', 'US-ETF', 'USD', 'NYSE', 'US-Energiesektor ETF', TRUE),
  ('XLV', 'Health Care Select Sector ETF', 'US-ETF', 'USD', 'NYSE', 'US-Gesundheitssektor ETF', TRUE),
  ('XLU', 'Utilities Select Sector ETF', 'US-ETF', 'USD', 'NYSE', 'US-Versorgungssektor ETF', TRUE),
  ('AAPL', 'Apple', 'US-Aktie', 'USD', 'NASDAQ', 'Apple Inc. — Consumer Electronics & Software', TRUE),
  ('MSFT', 'Microsoft', 'US-Aktie', 'USD', 'NASDAQ', 'Microsoft Corp. — Software & Cloud', TRUE),
  ('NVDA', 'Nvidia', 'US-Aktie', 'USD', 'NASDAQ', 'Nvidia Corp. — GPUs & KI-Chips', TRUE),
  ('AMZN', 'Amazon', 'US-Aktie', 'USD', 'NASDAQ', 'Amazon.com — E-Commerce & Cloud (AWS)', TRUE),
  ('GOOGL', 'Alphabet (Google)', 'US-Aktie', 'USD', 'NASDAQ', 'Alphabet Inc. — Suchmaschine & Werbung', TRUE),
  ('META', 'Meta Platforms', 'US-Aktie', 'USD', 'NASDAQ', 'Meta Platforms — Facebook, Instagram, WhatsApp', TRUE),
  ('TSLA', 'Tesla', 'US-Aktie', 'USD', 'NASDAQ', 'Tesla Inc. — Elektrofahrzeuge & Energie', TRUE),
  ('JPM', 'JPMorgan Chase', 'US-Aktie', 'USD', 'NYSE', 'JPMorgan Chase — größte US-Bank', TRUE),
  ('XOM', 'ExxonMobil', 'US-Aktie', 'USD', 'NYSE', 'ExxonMobil Corp. — Öl & Gas', TRUE),
  ('^GDAXI', 'DAX 40', 'EU-Index', 'EUR', 'XETRA', 'Deutscher Leitindex — 40 größte deutsche Unternehmen', TRUE),
  ('^MDAXI', 'MDAX', 'EU-Index', 'EUR', 'XETRA', 'Mid-Cap Deutschen Aktien — 50 Unternehmen', TRUE),
  ('^STOXX50E', 'Euro Stoxx 50', 'EU-Index', 'EUR', 'Euronext', '50 größte Eurozone-Unternehmen', TRUE),
  ('^FTSE', 'FTSE 100', 'EU-Index', 'GBP', 'LSE', 'Britischer Leitindex — 100 größte UK-Unternehmen', TRUE),
  ('^FCHI', 'CAC 40', 'EU-Index', 'EUR', 'Euronext Paris', 'Französischer Leitindex — 40 Unternehmen', TRUE),
  ('^SSMI', 'SMI (Schweiz)', 'EU-Index', 'CHF', 'SIX', 'Swiss Market Index — 20 größte Schweizer Unternehmen', TRUE),
  ('^N225', 'Nikkei 225', 'Asien-Index', 'JPY', 'TSE', 'Japanischer Leitindex — 225 Unternehmen', TRUE),
  ('^HSI', 'Hang Seng', 'Asien-Index', 'HKD', 'HKEX', 'Hongkonger Leitindex', TRUE),
  ('^KS11', 'KOSPI (Korea)', 'Asien-Index', 'KRW', 'KRX', 'Koreanischer Aktienindex', TRUE),
  ('GC=F', 'Gold Futures', 'Rohstoff', 'USD', 'COMEX', 'Gold Front-Month Futures ($/oz)', TRUE),
  ('SI=F', 'Silber Futures', 'Rohstoff', 'USD', 'COMEX', 'Silber Front-Month Futures ($/oz)', TRUE),
  ('CL=F', 'WTI Rohöl Futures', 'Rohstoff', 'USD', 'NYMEX', 'West Texas Intermediate Crude Oil ($/barrel)', TRUE),
  ('BZ=F', 'Brent Rohöl Futures', 'Rohstoff', 'USD', 'ICE', 'Brent Crude Oil ($/barrel)', TRUE),
  ('NG=F', 'Natural Gas Futures', 'Rohstoff', 'USD', 'NYMEX', 'Natural Gas Front-Month Futures', TRUE),
  ('ZC=F', 'Corn Futures (Mais)', 'Rohstoff', 'USD', 'CBOT', 'Corn (Mais) Front-Month Futures (cents/bushel)', TRUE),
  ('ZW=F', 'Wheat Futures (Weizen)', 'Rohstoff', 'USD', 'CBOT', 'Wheat (Weizen) Front-Month Futures', TRUE),
  ('ES=F', 'E-Mini S&P 500 Futures', 'Futures', 'USD', 'CME', 'E-Mini S&P 500 Front-Month Futures', TRUE),
  ('NQ=F', 'E-Mini Nasdaq 100 Futures', 'Futures', 'USD', 'CME', 'E-Mini Nasdaq 100 Front-Month Futures', TRUE),
  ('SAP', 'SAP', 'EU-Aktie', 'EUR', 'XETRA', 'SAP SE — Enterprise Software', TRUE),
  ('SIE.DE', 'Siemens', 'EU-Aktie', 'EUR', 'XETRA', 'Siemens AG — Industrie & Technologie', TRUE),
  ('ALV.DE', 'Allianz', 'EU-Aktie', 'EUR', 'XETRA', 'Allianz SE — Versicherung', TRUE),
  ('BAS.DE', 'BASF', 'EU-Aktie', 'EUR', 'XETRA', 'BASF SE — Chemie', TRUE),
  ('BMW.DE', 'BMW', 'EU-Aktie', 'EUR', 'XETRA', 'BMW AG — Automobil', TRUE),
  ('MBG.DE', 'Mercedes-Benz', 'EU-Aktie', 'EUR', 'XETRA', 'Mercedes-Benz Group — Automobil', TRUE),
  ('DTE.DE', 'Deutsche Telekom', 'EU-Aktie', 'EUR', 'XETRA', 'Deutsche Telekom AG', TRUE),
  ('ADS.DE', 'Adidas', 'EU-Aktie', 'EUR', 'XETRA', 'Adidas AG — Sportartikel', TRUE),
  ('ASML', 'ASML', 'EU-Aktie', 'EUR', 'Euronext', 'ASML Holding — Halbleiter-Lithografie', TRUE),
  ('MC.PA', 'LVMH', 'EU-Aktie', 'EUR', 'Euronext Paris', 'LVMH — Luxusgüter', TRUE),
  ('RO.SW', 'Roche', 'EU-Aktie', 'CHF', 'SIX', 'Roche Holding — Pharma & Diagnostik', TRUE),
  ('AZN', 'AstraZeneca', 'EU-Aktie', 'GBP', 'LSE', 'AstraZeneca — Pharma', TRUE),
  ('NVS', 'Novartis', 'EU-Aktie', 'CHF', 'SIX', 'Novartis AG — Pharma', TRUE),
  ('HSBC', 'HSBC', 'EU-Aktie', 'GBP', 'LSE', 'HSBC Holdings — Großbank', TRUE),
  ('SHEL', 'Shell', 'EU-Aktie', 'GBP', 'LSE', 'Shell plc — Öl & Gas', TRUE),
  ('NESN.SW', 'Nestlé', 'EU-Aktie', 'CHF', 'SIX', 'Nestlé SA — Lebensmittel', TRUE),
  ('LIN', 'Linde', 'EU-Aktie', 'EUR', 'XETRA', 'Linde plc — Industriegase', TRUE),
  ('OR.PA', 'L''Oréal', 'EU-Aktie', 'EUR', 'Euronext Paris', 'L''Oréal SA — Kosmetik', TRUE),
  ('PRX.AS', 'Prosus', 'EU-Aktie', 'EUR', 'Euronext Amsterdam', 'Prosus NV — Tech-Investment', TRUE),
  ('RMS.PA', 'Hermès', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Hermès International — Luxusgüter', TRUE),
  ('TTE', 'TotalEnergies', 'EU-Aktie', 'EUR', 'Euronext Paris', 'TotalEnergies SE — Energie', TRUE),
  ('ITX.MC', 'Inditex', 'EU-Aktie', 'EUR', 'BME Madrid', 'Inditex SA — Textil (Zara)', TRUE),
  ('SAN', 'Banco Santander', 'EU-Aktie', 'EUR', 'BME Madrid', 'Banco Santander — Großbank', TRUE),
  ('NVO', 'Novo Nordisk', 'EU-Aktie', 'DKK', 'Kopenhagen', 'Novo Nordisk — Pharma (Diabetes)', TRUE),
  ('ARM', 'Arm Holdings', 'EU-Aktie', 'GBP', 'NASDAQ', 'Arm Holdings — Chip-Design', TRUE),
  ('IBE.MC', 'Iberdrola', 'EU-Aktie', 'EUR', 'BME Madrid', 'Iberdrola SA — Energieversorger', TRUE),
  ('SU.PA', 'Schneider Electric', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Schneider Electric — Elektrotechnik', TRUE),
  ('AIR.PA', 'Airbus', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Airbus SE — Luft- & Raumfahrt', TRUE),
  ('RIO', 'Rio Tinto', 'EU-Aktie', 'GBP', 'LSE', 'Rio Tinto — Bergbau', TRUE),
  ('ENR.F', 'Siemens Energy', 'EU-Aktie', 'EUR', 'XETRA', 'Siemens Energy AG — Energietechnik', TRUE),
  ('ABBN.SW', 'ABB', 'EU-Aktie', 'CHF', 'SIX', 'ABB Ltd — Elektrotechnik & Automation', TRUE),
  ('ETN', 'Eaton', 'EU-Aktie', 'USD', 'NYSE', 'Eaton Corp — Elektro & Industrie (IR-Sitz)', TRUE),
  ('SAF.PA', 'Safran', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Safran SA — Luft- & Raumfahrt', TRUE),
  ('BUD', 'AB InBev', 'EU-Aktie', 'EUR', 'Euronext Brüssel', 'Anheuser-Busch InBev — Bier', TRUE),
  ('RR.L', 'Rolls-Royce', 'EU-Aktie', 'GBP', 'LSE', 'Rolls-Royce Holdings — Triebwerke', TRUE),
  ('CB', 'Chubb', 'EU-Aktie', 'USD', 'NYSE', 'Chubb Ltd — Versicherung (CH-Sitz)', TRUE),
  ('BTI', 'British American Tobacco', 'EU-Aktie', 'GBP', 'LSE', 'BAT — Tabak', TRUE),
  ('UL', 'Unilever', 'EU-Aktie', 'GBP', 'LSE', 'Unilever plc — Konsumgüter', TRUE),
  ('BBVA', 'BBVA', 'EU-Aktie', 'EUR', 'BME Madrid', 'Banco Bilbao Vizcaya Argentaria', TRUE),
  ('UBS', 'UBS', 'EU-Aktie', 'CHF', 'SIX', 'UBS Group AG — Großbank', TRUE),
  ('BP', 'BP', 'EU-Aktie', 'GBP', 'LSE', 'BP plc — Öl & Gas', TRUE),
  ('AI.PA', 'Air Liquide', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Air Liquide SA — Industriegase', TRUE),
  ('ACN', 'Accenture', 'EU-Aktie', 'USD', 'NYSE', 'Accenture plc — IT-Beratung (IR-Sitz)', TRUE),
  ('INVE-B.ST', 'Investor AB', 'EU-Aktie', 'SEK', 'Stockholm', 'Investor AB — Beteiligungsgesellschaft', TRUE),
  ('SNY', 'Sanofi', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Sanofi SA — Pharma', TRUE),
  ('ENEL.MI', 'Enel', 'EU-Aktie', 'EUR', 'Borsa Italiana', 'Enel SpA — Energieversorger', TRUE),
  ('UCG.MI', 'UniCredit', 'EU-Aktie', 'EUR', 'Borsa Italiana', 'UniCredit SpA — Großbank', TRUE),
  ('GSK', 'GSK', 'EU-Aktie', 'GBP', 'LSE', 'GSK plc — Pharma & Consumer Health', TRUE),
  ('MDT', 'Medtronic', 'EU-Aktie', 'USD', 'NYSE', 'Medtronic plc — Medizintechnik (IR-Sitz)', TRUE),
  ('ISP.MI', 'Intesa Sanpaolo', 'EU-Aktie', 'EUR', 'Borsa Italiana', 'Intesa Sanpaolo — Großbank', TRUE),
  ('BNP.PA', 'BNP Paribas', 'EU-Aktie', 'EUR', 'Euronext Paris', 'BNP Paribas — Großbank', TRUE),
  ('ZURN.SW', 'Zurich Insurance', 'EU-Aktie', 'CHF', 'SIX', 'Zurich Insurance Group — Versicherung', TRUE),
  ('CFR.SW', 'Richemont', 'EU-Aktie', 'CHF', 'SIX', 'Compagnie Financière Richemont — Luxusgüter', TRUE),
  ('EQNR', 'Equinor', 'EU-Aktie', 'NOK', 'Oslo', 'Equinor ASA — Energie', TRUE),
  ('EL.PA', 'EssilorLuxottica', 'EU-Aktie', 'EUR', 'Euronext Paris', 'EssilorLuxottica — Optik & Brillen', TRUE),
  ('SPOT', 'Spotify', 'EU-Aktie', 'USD', 'NYSE', 'Spotify Technology — Musik-Streaming (LU-Sitz)', TRUE),
  ('CS.PA', 'AXA', 'EU-Aktie', 'EUR', 'Euronext Paris', 'AXA SA — Versicherung', TRUE),
  ('TT', 'Trane Technologies', 'EU-Aktie', 'USD', 'NYSE', 'Trane Technologies — Klimatechnik (IR-Sitz)', TRUE),
  ('CDI.PA', 'Dior', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Christian Dior SE — Luxusgüter', TRUE),
  ('STX', 'Seagate', 'EU-Aktie', 'USD', 'NASDAQ', 'Seagate Technology — Datenspeicher (IR-Sitz)', TRUE),
  ('GLCNF', 'Glencore', 'EU-Aktie', 'USD', 'OTC', 'Glencore plc — Rohstoffhandel', TRUE),
  ('BA.L', 'BAE Systems', 'EU-Aktie', 'GBP', 'LSE', 'BAE Systems — Rüstung & Verteidigung', TRUE),
  ('CABK.MC', 'CaixaBank', 'EU-Aktie', 'EUR', 'BME Madrid', 'CaixaBank SA — Bank', TRUE),
  ('DG.PA', 'Vinci', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Vinci SA — Bau & Konzessionen', TRUE),
  ('ATCO-B.ST', 'Atlas Copco', 'EU-Aktie', 'SEK', 'Stockholm', 'Atlas Copco — Industriekompressoren', TRUE),
  ('NGG', 'National Grid', 'EU-Aktie', 'GBP', 'LSE', 'National Grid plc — Energienetze', TRUE),
  ('RHM.F', 'Rheinmetall', 'EU-Aktie', 'EUR', 'XETRA', 'Rheinmetall AG — Rüstung & Automobil', TRUE),
  ('ENGI.PA', 'ENGIE', 'EU-Aktie', 'EUR', 'Euronext Paris', 'ENGIE SA — Energieversorger', TRUE),
  ('JCI', 'Johnson Controls', 'EU-Aktie', 'USD', 'NYSE', 'Johnson Controls — Gebäudetechnik (IR-Sitz)', TRUE),
  ('E', 'ENI', 'EU-Aktie', 'USD', 'NYSE', 'ENI SpA — Öl & Gas (ADR)', TRUE),
  ('MUV2.DE', 'Munich Re', 'EU-Aktie', 'EUR', 'XETRA', 'Münchener Rückversicherung', TRUE),
  ('ING', 'ING', 'EU-Aktie', 'EUR', 'Euronext Amsterdam', 'ING Group — Bank', TRUE),
  ('LYG', 'Lloyds Banking', 'EU-Aktie', 'GBP', 'LSE', 'Lloyds Banking Group — Großbank (ADR)', TRUE),
  ('BCS', 'Barclays', 'EU-Aktie', 'GBP', 'LSE', 'Barclays plc — Großbank (ADR)', TRUE),
  ('CRH', 'CRH', 'EU-Aktie', 'USD', 'NYSE', 'CRH plc — Baustoffe (IR-Sitz)', TRUE),
  ('AON', 'Aon', 'EU-Aktie', 'USD', 'NYSE', 'Aon plc — Versicherungsmakler (IR-Sitz)', TRUE),
  ('VOLV-A.ST', 'Volvo', 'EU-Aktie', 'SEK', 'Stockholm', 'Volvo Group — LKW & Baumaschinen', TRUE),
  ('HO.PA', 'Thales', 'EU-Aktie', 'EUR', 'Euronext Paris', 'Thales SA — Verteidigung & Elektronik', TRUE),
  ('G.MI', 'Generali', 'EU-Aktie', 'EUR', 'Borsa Italiana', 'Assicurazioni Generali — Versicherung', TRUE),
  ('BRK-B', 'Berkshire Hathaway B', 'US-Aktie', 'USD', 'NYSE', 'Berkshire Hathaway — Warren Buffett', TRUE),
  ('V', 'Visa', 'US-Aktie', 'USD', 'NYSE', 'Visa Inc. — Zahlungsnetzwerk', TRUE),
  ('JNJ', 'Johnson & Johnson', 'US-Aktie', 'USD', 'NYSE', 'J&J — Pharma & Consumer Health', TRUE),
  ('WMT', 'Walmart', 'US-Aktie', 'USD', 'NYSE', 'Walmart Inc. — Einzelhandel', TRUE),
  ('PG', 'Procter & Gamble', 'US-Aktie', 'USD', 'NYSE', 'P&G — Konsumgüter', TRUE),
  ('UNH', 'UnitedHealth', 'US-Aktie', 'USD', 'NYSE', 'UnitedHealth Group — Krankenversicherung', TRUE),
  ('HD', 'Home Depot', 'US-Aktie', 'USD', 'NYSE', 'Home Depot — Baumarkt-Kette', TRUE),
  ('MA', 'Mastercard', 'US-Aktie', 'USD', 'NYSE', 'Mastercard Inc. — Zahlungsnetzwerk', TRUE),
  ('AVGO', 'Broadcom', 'US-Aktie', 'USD', 'NASDAQ', 'Broadcom Inc. — Halbleiter & Infrastruktur', TRUE),
  ('LLY', 'Eli Lilly', 'US-Aktie', 'USD', 'NYSE', 'Eli Lilly — Pharma (Diabetes, Adipositas)', TRUE),
  ('ORCL', 'Oracle', 'US-Aktie', 'USD', 'NYSE', 'Oracle Corp. — Datenbanken & Cloud', TRUE),
  ('COST', 'Costco', 'US-Aktie', 'USD', 'NASDAQ', 'Costco Wholesale — Großhandel', TRUE),
  ('MU', 'Micron', 'US-Aktie', 'USD', 'NASDAQ', 'Micron Technology — Speicherchips', TRUE),
  ('NFLX', 'Netflix', 'US-Aktie', 'USD', 'NASDAQ', 'Netflix Inc. — Streaming', TRUE),
  ('CVX', 'Chevron', 'US-Aktie', 'USD', 'NYSE', 'Chevron Corp. — Öl & Gas', TRUE),
  ('ABBV', 'AbbVie', 'US-Aktie', 'USD', 'NYSE', 'AbbVie Inc. — Pharma (Immunologie)', TRUE),
  ('BAC', 'Bank of America', 'US-Aktie', 'USD', 'NYSE', 'Bank of America — Großbank', TRUE),
  ('PLTR', 'Palantir', 'US-Aktie', 'USD', 'NYSE', 'Palantir Technologies — KI & Datenanalyse', TRUE),
  ('AMD', 'AMD', 'US-Aktie', 'USD', 'NASDAQ', 'Advanced Micro Devices — Halbleiter', TRUE),
  ('CAT', 'Caterpillar', 'US-Aktie', 'USD', 'NYSE', 'Caterpillar Inc. — Baumaschinen', TRUE),
  ('KO', 'Coca-Cola', 'US-Aktie', 'USD', 'NYSE', 'The Coca-Cola Company — Getränke', TRUE),
  ('CSCO', 'Cisco', 'US-Aktie', 'USD', 'NASDAQ', 'Cisco Systems — Netzwerktechnik', TRUE),
  ('GE', 'GE Aerospace', 'US-Aktie', 'USD', 'NYSE', 'GE Aerospace — Triebwerke & Luftfahrt', TRUE),
  ('MRK', 'Merck', 'US-Aktie', 'USD', 'NYSE', 'Merck & Co. — Pharma', TRUE),
  ('AMAT', 'Applied Materials', 'US-Aktie', 'USD', 'NASDAQ', 'Applied Materials — Halbleiter-Equipment', TRUE),
  ('LRCX', 'Lam Research', 'US-Aktie', 'USD', 'NASDAQ', 'Lam Research — Halbleiter-Equipment', TRUE),
  ('GS', 'Goldman Sachs', 'US-Aktie', 'USD', 'NYSE', 'Goldman Sachs — Investmentbank', TRUE),
  ('MS', 'Morgan Stanley', 'US-Aktie', 'USD', 'NYSE', 'Morgan Stanley — Investmentbank', TRUE),
  ('RTX', 'RTX Corp', 'US-Aktie', 'USD', 'NYSE', 'RTX Corp. — Rüstung (Raytheon)', TRUE),
  ('WFC', 'Wells Fargo', 'US-Aktie', 'USD', 'NYSE', 'Wells Fargo — Großbank', TRUE),
  ('PM', 'Philip Morris', 'US-Aktie', 'USD', 'NYSE', 'Philip Morris International — Tabak', TRUE),
  ('INTC', 'Intel', 'US-Aktie', 'USD', 'NASDAQ', 'Intel Corp. — Halbleiter', TRUE),
  ('GEV', 'GE Vernova', 'US-Aktie', 'USD', 'NYSE', 'GE Vernova — Energietechnik', TRUE),
  ('IBM', 'IBM', 'US-Aktie', 'USD', 'NYSE', 'IBM — IT & Cloud', TRUE),
  ('TMUS', 'T-Mobile US', 'US-Aktie', 'USD', 'NASDAQ', 'T-Mobile US — Telekommunikation', TRUE),
  ('MCD', 'McDonald''s', 'US-Aktie', 'USD', 'NYSE', 'McDonald''s Corp. — Fast Food', TRUE),
  ('PEP', 'PepsiCo', 'US-Aktie', 'USD', 'NASDAQ', 'PepsiCo Inc. — Getränke & Snacks', TRUE),
  ('AXP', 'American Express', 'US-Aktie', 'USD', 'NYSE', 'American Express — Finanzdienstleistungen', TRUE),
  ('VZ', 'Verizon', 'US-Aktie', 'USD', 'NYSE', 'Verizon Communications — Telekommunikation', TRUE),
  ('C', 'Citigroup', 'US-Aktie', 'USD', 'NYSE', 'Citigroup Inc. — Großbank', TRUE),
  ('KLAC', 'KLA Corp', 'US-Aktie', 'USD', 'NASDAQ', 'KLA Corp. — Halbleiter-Inspektion', TRUE),
  ('T', 'AT&T', 'US-Aktie', 'USD', 'NYSE', 'AT&T Inc. — Telekommunikation', TRUE),
  ('NEE', 'NextEra Energy', 'US-Aktie', 'USD', 'NYSE', 'NextEra Energy — Erneuerbare Energien', TRUE),
  ('AMGN', 'Amgen', 'US-Aktie', 'USD', 'NASDAQ', 'Amgen Inc. — Biotech', TRUE),
  ('TMO', 'Thermo Fisher', 'US-Aktie', 'USD', 'NYSE', 'Thermo Fisher Scientific — Life Sciences', TRUE),
  ('ABT', 'Abbott Labs', 'US-Aktie', 'USD', 'NYSE', 'Abbott Laboratories — Medizintechnik', TRUE),
  ('TXN', 'Texas Instruments', 'US-Aktie', 'USD', 'NASDAQ', 'Texas Instruments — Halbleiter', TRUE),
  ('TJX', 'TJX Companies', 'US-Aktie', 'USD', 'NYSE', 'TJX Companies — Einzelhandel (TK Maxx)', TRUE),
  ('GILD', 'Gilead Sciences', 'US-Aktie', 'USD', 'NASDAQ', 'Gilead Sciences — Biotech (HIV, Hepatitis)', TRUE),
  ('CRM', 'Salesforce', 'US-Aktie', 'USD', 'NYSE', 'Salesforce Inc. — CRM-Software', TRUE),
  ('DIS', 'Disney', 'US-Aktie', 'USD', 'NYSE', 'Walt Disney Company — Unterhaltung', TRUE),
  ('ISRG', 'Intuitive Surgical', 'US-Aktie', 'USD', 'NASDAQ', 'Intuitive Surgical — Chirurgie-Roboter', TRUE),
  ('SCHW', 'Charles Schwab', 'US-Aktie', 'USD', 'NYSE', 'Charles Schwab — Brokerage', TRUE),
  ('BA', 'Boeing', 'US-Aktie', 'USD', 'NYSE', 'Boeing Company — Luft- & Raumfahrt', TRUE),
  ('PFE', 'Pfizer', 'US-Aktie', 'USD', 'NYSE', 'Pfizer Inc. — Pharma', TRUE),
  ('BLK', 'BlackRock', 'US-Aktie', 'USD', 'NYSE', 'BlackRock Inc. — Vermögensverwaltung', TRUE),
  ('ADI', 'Analog Devices', 'US-Aktie', 'USD', 'NASDAQ', 'Analog Devices — Halbleiter', TRUE),
  ('APH', 'Amphenol', 'US-Aktie', 'USD', 'NYSE', 'Amphenol Corp. — Elektronik-Steckverbinder', TRUE),
  ('ANET', 'Arista Networks', 'US-Aktie', 'USD', 'NYSE', 'Arista Networks — Netzwerk-Hardware', TRUE),
  ('COP', 'ConocoPhillips', 'US-Aktie', 'USD', 'NYSE', 'ConocoPhillips — Öl & Gas', TRUE),
  ('DE', 'Deere & Company', 'US-Aktie', 'USD', 'NYSE', 'John Deere — Landmaschinen', TRUE),
  ('UBER', 'Uber', 'US-Aktie', 'USD', 'NYSE', 'Uber Technologies — Mobilität & Lieferung', TRUE),
  ('UNP', 'Union Pacific', 'US-Aktie', 'USD', 'NYSE', 'Union Pacific Corp. — Eisenbahn', TRUE),
  ('HON', 'Honeywell', 'US-Aktie', 'USD', 'NASDAQ', 'Honeywell International — Industrie-Konglomerat', TRUE),
  ('BX', 'Blackstone', 'US-Aktie', 'USD', 'NYSE', 'Blackstone Inc. — Private Equity', TRUE),
  ('LMT', 'Lockheed Martin', 'US-Aktie', 'USD', 'NYSE', 'Lockheed Martin — Rüstung & Verteidigung', TRUE),
  ('WELL', 'Welltower', 'US-Aktie', 'USD', 'NYSE', 'Welltower Inc. — Gesundheits-REIT', TRUE),
  ('QCOM', 'Qualcomm', 'US-Aktie', 'USD', 'NASDAQ', 'Qualcomm Inc. — Mobilfunk-Chips', TRUE),
  ('DHR', 'Danaher', 'US-Aktie', 'USD', 'NYSE', 'Danaher Corp. — Life Sciences & Diagnostik', TRUE),
  ('BKNG', 'Booking Holdings', 'US-Aktie', 'USD', 'NASDAQ', 'Booking Holdings — Online-Reisebuchung', TRUE),
  ('LOW', 'Lowe''s', 'US-Aktie', 'USD', 'NYSE', 'Lowe''s Companies — Baumarkt', TRUE),
  ('APP', 'AppLovin', 'US-Aktie', 'USD', 'NASDAQ', 'AppLovin Corp. — Mobile Werbung & KI', TRUE),
  ('PANW', 'Palo Alto Networks', 'US-Aktie', 'USD', 'NASDAQ', 'Palo Alto Networks — Cybersecurity', TRUE),
  ('PLD', 'Prologis', 'US-Aktie', 'USD', 'NYSE', 'Prologis Inc. — Logistik-REIT', TRUE),
  ('SPGI', 'S&P Global', 'US-Aktie', 'USD', 'NYSE', 'S&P Global — Ratings & Finanzdata', TRUE),
  ('SYK', 'Stryker', 'US-Aktie', 'USD', 'NYSE', 'Stryker Corp. — Medizintechnik', TRUE),
  ('BMY', 'Bristol-Myers Squibb', 'US-Aktie', 'USD', 'NYSE', 'Bristol-Myers Squibb — Pharma', TRUE),
  ('GLW', 'Corning', 'US-Aktie', 'USD', 'NYSE', 'Corning Inc. — Spezialglas & Glasfaser', TRUE),
  ('NEM', 'Newmont', 'US-Aktie', 'USD', 'NYSE', 'Newmont Corp. — Goldbergbau', TRUE),
  ('INTU', 'Intuit', 'US-Aktie', 'USD', 'NASDAQ', 'Intuit Inc. — Finanzsoftware (TurboTax)', TRUE),
  ('PH', 'Parker-Hannifin', 'US-Aktie', 'USD', 'NYSE', 'Parker-Hannifin — Hydraulik & Pneumatik', TRUE),
  ('COF', 'Capital One', 'US-Aktie', 'USD', 'NYSE', 'Capital One Financial — Kreditkarten', TRUE),
  ('VRTX', 'Vertex Pharma', 'US-Aktie', 'USD', 'NASDAQ', 'Vertex Pharmaceuticals — Biotech (Mukoviszidose)', TRUE),
  ('PGR', 'Progressive', 'US-Aktie', 'USD', 'NYSE', 'Progressive Corp. — Kfz-Versicherung', TRUE),
  ('NOW', 'ServiceNow', 'US-Aktie', 'USD', 'NYSE', 'ServiceNow Inc. — IT-Workflow-Software', TRUE),
  ('DELL', 'Dell Technologies', 'US-Aktie', 'USD', 'NYSE', 'Dell Technologies — PCs & Server', TRUE),
  ('MO', 'Altria', 'US-Aktie', 'USD', 'NYSE', 'Altria Group — Tabak (Marlboro)', TRUE),
  ('SO', 'Southern Company', 'US-Aktie', 'USD', 'NYSE', 'Southern Company — Energieversorger', TRUE),
  ('CME', 'CME Group', 'US-Aktie', 'USD', 'NASDAQ', 'CME Group — Terminbörse (Futures)', TRUE),
  ('MCK', 'McKesson', 'US-Aktie', 'USD', 'NYSE', 'McKesson Corp. — Pharma-Distribution', TRUE),
  ('HCA', 'HCA Healthcare', 'US-Aktie', 'USD', 'NYSE', 'HCA Healthcare — Krankenhauskette', TRUE),
  ('SBUX', 'Starbucks', 'US-Aktie', 'USD', 'NASDAQ', 'Starbucks Corp. — Kaffee-Kette', TRUE),
  ('DUK', 'Duke Energy', 'US-Aktie', 'USD', 'NYSE', 'Duke Energy — Energieversorger', TRUE),
  ('CEG', 'Constellation Energy', 'US-Aktie', 'USD', 'NASDAQ', 'Constellation Energy — Kernkraft & Erneuerbare', TRUE),
  ('CMCSA', 'Comcast', 'US-Aktie', 'USD', 'NASDAQ', 'Comcast Corp. — Kabel & Medien', TRUE),
  ('CRWD', 'CrowdStrike', 'US-Aktie', 'USD', 'NASDAQ', 'CrowdStrike Holdings — Cybersecurity', TRUE),
  ('NOC', 'Northrop Grumman', 'US-Aktie', 'USD', 'NYSE', 'Northrop Grumman — Rüstung & Raumfahrt', TRUE),
  ('ADBE', 'Adobe', 'US-Aktie', 'USD', 'NASDAQ', 'Adobe Inc. — Kreativ-Software', TRUE),
  ('EQIX', 'Equinix', 'US-Aktie', 'USD', 'NASDAQ', 'Equinix Inc. — Rechenzentren-REIT', TRUE),
  ('HWM', 'Howmet Aerospace', 'US-Aktie', 'USD', 'NYSE', 'Howmet Aerospace — Luft- & Raumfahrt-Teile', TRUE),
  ('GD', 'General Dynamics', 'US-Aktie', 'USD', 'NYSE', 'General Dynamics — Rüstung & IT', TRUE),
  ('BSX', 'Boston Scientific', 'US-Aktie', 'USD', 'NYSE', 'Boston Scientific — Medizintechnik', TRUE),
  ('WM', 'Waste Management', 'US-Aktie', 'USD', 'NYSE', 'Waste Management — Abfallentsorgung', TRUE),
  ('CVS', 'CVS Health', 'US-Aktie', 'USD', 'NYSE', 'CVS Health — Apotheken & Krankenversicherung', TRUE),
  ('ICE', 'Intercontinental Exchange', 'US-Aktie', 'USD', 'NYSE', 'ICE — Börsen-Betreiber (NYSE)', TRUE),
  ('FCX', 'Freeport-McMoRan', 'US-Aktie', 'USD', 'NYSE', 'Freeport-McMoRan — Kupfer & Gold', TRUE),
  ('MAR', 'Marriott', 'US-Aktie', 'USD', 'NASDAQ', 'Marriott International — Hotels', TRUE),
  ('WMB', 'Williams Companies', 'US-Aktie', 'USD', 'NYSE', 'Williams Companies — Gas-Pipelines', TRUE),
  ('XLI', 'Industrials Select Sector ETF', 'US-ETF', 'USD', 'NYSE', 'US-Industriesektor ETF', TRUE),
  ('XLC', 'Communication Services ETF', 'US-ETF', 'USD', 'NYSE', 'US-Kommunikationssektor ETF', TRUE),
  ('XLB', 'Materials Select Sector ETF', 'US-ETF', 'USD', 'NYSE', 'US-Grundstoffsektor ETF', TRUE),
  ('XLP', 'Consumer Staples Select ETF', 'US-ETF', 'USD', 'NYSE', 'US-Basiskonsumgüter ETF', TRUE),
  ('XLY', 'Consumer Discretionary ETF', 'US-ETF', 'USD', 'NYSE', 'US-Zyklische Konsumgüter ETF', TRUE),
  ('SHY', 'iShares 1-3Y Treasury ETF', 'Anleihen', 'USD', 'NYSE', 'Kurzläufer US-Staatsanleihen', TRUE),
  ('IEF', 'iShares 7-10Y Treasury ETF', 'Anleihen', 'USD', 'NYSE', 'Mittelfristige US-Staatsanleihen', TRUE),
  ('HYG', 'iShares High Yield Corp Bond', 'Anleihen', 'USD', 'NYSE', 'US High-Yield Unternehmensanleihen', TRUE),
  ('EEM', 'iShares MSCI EM ETF', 'Emerging Markets', 'USD', 'NYSE', 'Schwellenländer ETF', TRUE),
  ('FXI', 'iShares China Large-Cap ETF', 'Emerging Markets', 'USD', 'NYSE', 'China Large-Cap ETF', TRUE),
  ('EWZ', 'iShares MSCI Brazil ETF', 'Emerging Markets', 'USD', 'NYSE', 'Brasilien ETF', TRUE),
  ('^SDAXI', 'SDAX', 'EU-Index', 'EUR', 'XETRA', 'Small-Cap Deutsche Aktien', TRUE),
  ('^TECDAX', 'TecDAX', 'EU-Index', 'EUR', 'XETRA', 'Deutsche Technologie-Aktien', TRUE),
  ('^IBEX', 'IBEX 35', 'EU-Index', 'EUR', 'BME', 'Spanischer Leitindex', TRUE),
  ('HG=F', 'Copper Futures (Kupfer)', 'Rohstoff', 'USD', 'COMEX', 'Kupfer Futures ($/lb)', TRUE),
  ('PL=F', 'Platinum Futures (Platin)', 'Rohstoff', 'USD', 'NYMEX', 'Platin Futures ($/oz)', TRUE),
  ('ZS=F', 'Soybean Futures (Sojabohnen)', 'Rohstoff', 'USD', 'CBOT', 'Sojabohnen Futures', TRUE),
  ('BTC-USD', 'Bitcoin (USD)', 'Krypto', 'USD', 'Crypto', 'Bitcoin / US-Dollar', TRUE),
  ('ETH-USD', 'Ethereum (USD)', 'Krypto', 'USD', 'Crypto', 'Ethereum / US-Dollar', TRUE),
  ('SOL-USD', 'Solana (USD)', 'Krypto', 'USD', 'Crypto', 'Solana / US-Dollar', TRUE),
  ('XRP-USD', 'XRP (Ripple)', 'Krypto', 'USD', 'Crypto', 'XRP / US-Dollar', TRUE),
  ('ADA-USD', 'Cardano', 'Krypto', 'USD', 'Crypto', 'Cardano / US-Dollar', TRUE),
  ('DOGE-USD', 'Dogecoin', 'Krypto', 'USD', 'Crypto', 'Dogecoin / US-Dollar', TRUE),
  ('EURUSD=X', 'EUR/USD', 'FX', 'USD', 'Forex', 'Euro / US-Dollar Wechselkurs', TRUE),
  ('GBPUSD=X', 'GBP/USD', 'FX', 'USD', 'Forex', 'Britisches Pfund / US-Dollar', TRUE),
  ('USDJPY=X', 'USD/JPY', 'FX', 'JPY', 'Forex', 'US-Dollar / Japanischer Yen', TRUE),
  ('USDCHF=X', 'USD/CHF', 'FX', 'CHF', 'Forex', 'US-Dollar / Schweizer Franken', TRUE),
  ('AUDUSD=X', 'AUD/USD', 'FX', 'USD', 'Forex', 'Australischer Dollar / US-Dollar', TRUE),
  ('NZDUSD=X', 'NZD/USD', 'FX', 'USD', 'Forex', 'Neuseeland Dollar / US-Dollar', TRUE),
  ('USDCAD=X', 'USD/CAD', 'FX', 'CAD', 'Forex', 'US-Dollar / Kanadischer Dollar', TRUE),
  ('EURGBP=X', 'EUR/GBP', 'FX', 'GBP', 'Forex', 'Euro / Britisches Pfund', TRUE),
  ('EURJPY=X', 'EUR/JPY', 'FX', 'JPY', 'Forex', 'Euro / Japanischer Yen', TRUE),
  ('EURCHF=X', 'EUR/CHF', 'FX', 'CHF', 'Forex', 'Euro / Schweizer Franken', TRUE),
  ('GBPJPY=X', 'GBP/JPY', 'FX', 'JPY', 'Forex', 'Britisches Pfund / Japanischer Yen', TRUE)
ON CONFLICT (ticker) DO UPDATE SET
  name=EXCLUDED.name, kategorie=EXCLUDED.kategorie, waehrung=EXCLUDED.waehrung,
  exchange=EXCLUDED.exchange, beschreibung=EXCLUDED.beschreibung,
  aktiv=EXCLUDED.aktiv, updated_at=NOW();

-- Danach: PostgREST-Schema-Cache neu laden (Supabase macht das automatisch nach DDL,
-- sonst: Project Settings -> API -> Reload schema, oder NOTIFY pgrst, ''reload schema'';)
NOTIFY pgrst, 'reload schema';
